"""Identity rules.

Source of truth: docs/contracts/canonical-event-contract.md section 5
(Identity & Traceability) and the validation & correction report
section 10 (Broker vs System Ownership).

System-owned ids are UUID strings and are never reused.
Broker-owned ids are opaque external strings, recorded verbatim and
never fabricated or generated by this codebase.
"""

from __future__ import annotations

import re

UUID_PATTERN = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")

SYSTEM_ID_FIELDS = (
    "event_id",
    "trade_id",
    "correlation_id",
    "inference_id",
    "reconciliation_id",
)

BROKER_ID_FIELDS = (
    "broker_order_id",
    "broker_deal_id",
    "broker_position_id",
)

BROKER_ID_MAX_LENGTH = 128


def is_valid_system_id(value: object) -> bool:
    """True when *value* is a valid system-owned UUID string."""
    return isinstance(value, str) and UUID_PATTERN.fullmatch(value) is not None


def is_valid_broker_id(value: object) -> bool:
    """True when *value* is a valid external broker id string.

    Broker ids are opaque, non-empty strings without control characters.
    They are never generated here and are preserved verbatim.
    """
    if not isinstance(value, str) or not value:
        return False
    if len(value) > BROKER_ID_MAX_LENGTH:
        return False
    return not any(ord(ch) < 32 or ord(ch) == 127 for ch in value)
