"""Deterministic reason codes for Risk Engine decisions."""

from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    """Deterministic reason code enum for System Risk Gate decisions."""

    APPROVED = "APPROVED"
    AI_NO_TRADE = "AI_NO_TRADE"
    INVALID_MARKET_CONTEXT = "INVALID_MARKET_CONTEXT"
    INVALID_ACCOUNT_STATE = "INVALID_ACCOUNT_STATE"
    SPREAD_TOO_HIGH = "SPREAD_TOO_HIGH"
    DRAWDOWN_LIMIT = "DRAWDOWN_LIMIT"
    EXPOSURE_LIMIT = "EXPOSURE_LIMIT"
    INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN"
    LOT_OUT_OF_RANGE = "LOT_OUT_OF_RANGE"
    LOT_STEP_INVALID = "LOT_STEP_INVALID"
    RISK_LIMIT = "RISK_LIMIT"
    INVALID_SL = "INVALID_SL"
    BROKER_CONSTRAINT = "BROKER_CONSTRAINT"
    STALE_CONTEXT = "STALE_CONTEXT"
    UNKNOWN_RISK_INPUT = "UNKNOWN_RISK_INPUT"
    AUTHORITY_VIOLATION = "AUTHORITY_VIOLATION"
