"""Deterministic payload factories for the 17 canonical event types.

All values are synthetic; broker ids are opaque external strings that
must never be generated by production code (only here, for fixtures).
"""

from __future__ import annotations

from shared.contracts.types import EventType

TRADE_ID = "3f2c9b1e-7d4a-4b8e-9c2f-0d1e2f3a4b5c"
CORRELATION_ID = "8a1b2c3d-4e5f-4a6b-9c7d-0e1f2a3b4c5d"
INFERENCE_ID = "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d"
RECONCILIATION_ID = "6f7e8d9c-0b1a-4c2d-8e3f-4a5b6c7d8e9f"

BROKER_ORDER_ID = "broker-order-001"
BROKER_DEAL_ID = "broker-deal-001"
BROKER_POSITION_ID = "broker-position-001"

TS = "2026-08-14T09:00:00Z"
TS_MS = "2026-08-14T09:00:00.000Z"
MONO = 1_000_000


def tick_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "symbol": "XAUUSD",
        "bid": 2000.0,
        "ask": 2000.5,
        "mid": 2000.25,
        "spread": 0.5,
        "ts_source": TS,
    }
    payload.update(overrides)
    return payload


def trigger_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "trigger_source": "TECHNICAL",
        "trigger_category": "momentum",
        "trigger_metadata": {"window": "m5"},
        "context_reference": "ctx-1",
    }
    payload.update(overrides)
    return payload


def context_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "symbol": "XAUUSD",
        "m1_context_ref": "ctx-m1-1",
        "m5_context_ref": "ctx-m5-1",
        "atr_m1": 1.25,
        "context_snapshot_id": "snap-1",
    }
    payload.update(overrides)
    return payload


def ai_request_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "inference_id": INFERENCE_ID,
        "request_ts": TS,
        "context_snapshot_id": "snap-1",
    }
    payload.update(overrides)
    return payload


def ai_response_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "inference_id": INFERENCE_ID,
        "decision": "BUY",
        "confidence": 0.82,
        "reason": "momentum confirmed",
        "latency_ms": 45.5,
        "valid": True,
    }
    payload.update(overrides)
    return payload


def risk_gate_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "gate_result": "ALLOW",
        "risk_budget_usd": 100.0,
        "candidate_lot": 0.1,
        "final_lot": 0.1,
        "aggregate_risk_usd": 55.0,
        "aggregate_exposure_usd": 2000.0,
        "free_margin_usd": 5000.0,
    }
    payload.update(overrides)
    return payload


def order_submitted_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "requested_price": 2000.25,
        "requested_volume": 0.1,
        "direction": "BUY",
        "order_type": "MARKET",
        "submission_ts": TS,
    }
    payload.update(overrides)
    return payload


def order_acknowledged_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "broker_order_id": BROKER_ORDER_ID,
        "broker_state": "FILLED",
        "ack_ts": TS,
    }
    payload.update(overrides)
    return payload


def order_filled_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "broker_order_id": BROKER_ORDER_ID,
        "broker_deal_id": BROKER_DEAL_ID,
        "fill_price": 2000.3,
        "fill_volume": 0.1,
        "slippage": 0.05,
        "fill_ts": TS,
    }
    payload.update(overrides)
    return payload


def position_opened_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "broker_position_id": BROKER_POSITION_ID,
        "direction": "BUY",
        "volume": 0.1,
        "open_price": 2000.3,
        "open_ts": TS,
        "state": "OPEN",
    }
    payload.update(overrides)
    return payload


def position_updated_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "broker_position_id": BROKER_POSITION_ID,
        "current_price": 2010.0,
        "running_pnl_usd": 9.7,
        "running_net_pnl_usd": 8.9,
        "mfe_usd": 12.0,
        "mae_usd": -3.0,
        "spread_current": 0.4,
    }
    payload.update(overrides)
    return payload


def net_profit_positive_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "broker_position_id": BROKER_POSITION_ID,
        "trade_id": TRADE_ID,
        "running_net_pnl_usd": 15.0,
        "detection_ts": TS,
        "observed_bid": 2010.0,
        "observed_ask": 2010.5,
        "spread_at_detection": 0.5,
        "reason": "NET_PROFIT_THRESHOLD_CROSSED",
    }
    payload.update(overrides)
    return payload


def exit_submitted_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "broker_position_id": BROKER_POSITION_ID,
        "requested_close_price": 2010.0,
        "close_volume": 0.1,
        "submission_ts": TS,
    }
    payload.update(overrides)
    return payload


def position_closed_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "broker_position_id": BROKER_POSITION_ID,
        "exit_fill_price": 2010.0,
        "exit_fill_volume": 0.1,
        "exit_fill_ts": TS,
        "realized_pnl_usd": 9.7,
        "transaction_cost_usd": 0.8,
        "net_pnl_usd": 8.9,
        "exit_reason": "TAKE_PROFIT",
        "final_state": "CLOSED",
    }
    payload.update(overrides)
    return payload


def reconciliation_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "reconciliation_id": RECONCILIATION_ID,
        "trigger": "HEARTBEAT",
        "local_state": "OPEN",
        "broker_state": "OPEN",
        "mismatch": False,
        "result": "SYNCED",
        "action": "NONE",
        "ts": TS,
    }
    payload.update(overrides)
    return payload


def error_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "error_code": "ERR_001",
        "component": "collector",
        "severity": "ERROR",
        "message": "synthetic error",
    }
    payload.update(overrides)
    return payload


def timeout_payload(**overrides: object) -> dict[str, object]:
    payload: dict[str, object] = {
        "timeout_code": "TIMEOUT_001",
        "component": "collector",
        "severity": "WARN",
        "message": "synthetic timeout",
    }
    payload.update(overrides)
    return payload


def valid_payload_for(event_type: EventType) -> dict[str, object]:
    """Return a valid payload dict for any of the 17 canonical types."""
    builders = {
        EventType.TICK_RECEIVED: tick_payload,
        EventType.TRIGGER_DETECTED: trigger_payload,
        EventType.CONTEXT_BUILT: context_payload,
        EventType.AI_REQUEST: ai_request_payload,
        EventType.AI_RESPONSE: ai_response_payload,
        EventType.RISK_GATE: risk_gate_payload,
        EventType.ORDER_SUBMITTED: order_submitted_payload,
        EventType.ORDER_ACKNOWLEDGED: order_acknowledged_payload,
        EventType.ORDER_FILLED: order_filled_payload,
        EventType.POSITION_OPENED: position_opened_payload,
        EventType.POSITION_UPDATED: position_updated_payload,
        EventType.NET_PROFIT_POSITIVE: net_profit_positive_payload,
        EventType.EXIT_SUBMITTED: exit_submitted_payload,
        EventType.POSITION_CLOSED: position_closed_payload,
        EventType.RECONCILIATION: reconciliation_payload,
        EventType.ERROR: error_payload,
        EventType.TIMEOUT: timeout_payload,
    }
    return builders[event_type]()
